### ISSUE TITLE
Allow to display the rendered HTML contents

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/swiftmailer-bundle#114] opened 2015-09-28 14:42 UTC
When displaying a real email (like a newsletter) it would be very useful if we allowed to view the rendered HTML content instead of just the HTML tags.

**Comment by stof** [comment] 2015-09-28 14:59
A solution for this is to use an iframe in which the HTML content is rendered.
Doing it without requiring people to register a routing resource could be done using the same trick than in DoctrineBundle for the ``explain`` case, but it is kind of hacky.

**Comment by fabpot** [comment] 2017-03-21 21:22
duplicate of #86

**Closed by fabpot** 2017-03-21 21:22 UTC
