### ISSUE TITLE
[feature] Render HTML email in Profiler

### ISSUE THREAD

**Issue by FredoVelcro** [symfony/swiftmailer-bundle#86] opened 2014-10-13 12:11 UTC
In the WebProfiler, it would be nice to render the resulting HTML of spooled emails of type "text/html" (with a button that opens a popup for instance...)

**Comment by hason** [comment] 2015-10-01 09:10
Partially resolved in #109 and duplicate of #114.

**Comment by romain-pierre** [comment] 2017-03-21 18:10
Can an admin closes the duplicate #114? I suggest to work on this feature now.

**Comment by romain-pierre** [comment] 2017-03-21 22:24
This is a mookup of what i'm planning to do for this feature.

<img width="1280" alt="screen shot 2017-03-21 at 23 13 55" src="https://cloud.githubusercontent.com/assets/20155356/24173452/7087760e-0e8c-11e7-91d6-2384cd57e674.png">

Each email is displayed in the "Message" tab if a "part" is compliant with the web browser (first HTML, then text...). Source tab contains the headers and contents. Details tab display all system information about the email. To be more reliable, I use a base64 encoded version of the message in an iframe.

**Comment by fabpot** [comment] 2018-02-14 08:17
Implemented as of v3.2.0. @romain-pierre I didn't see your input here before merging the PR from @javiereguiluz. Your mockup looks very interesting. Would you like to submit a PR that improves what we have now?

**Closed by fabpot** 2018-02-14 08:17 UTC

**Comment by esynaps** [comment] 2020-04-22 14:47
Feature always interesting, any news?
