### ISSUE TITLE
Allow to specify a command option for sendmail transport

### ISSUE THREAD

**Issue by Gregoire-M** [symfony/swiftmailer-bundle#20] opened 2012-08-24 11:52 UTC
The sendmail transport uses a UNIX command to send mails. The default command is `/usr/sbin/sendmail -bs`. There is currently no way to modify it through the bundle configuration.

**Comment by tobiasmuehl** [comment] 2017-06-02 04:22
Has this been added yet?

**Comment by mhdev90** [comment] 2017-08-08 09:22
Look at this pull request: https://github.com/symfony/swiftmailer-bundle/pull/185.

**Comment by kojiDev** [comment] 2019-02-01 19:49
The issue is obsolete. Would someone come along and close it?

**Closed** 2019-02-01 19:50 UTC
